### ISSUE TITLE
NullPointerException in SearchRequestBuilder.class

### ISSUE THREAD

**Issue by suvera** [pingidentity/scim2#150]
JAVA: **1.8**
scim2sdk: **2.3.5**
Jackson: **2.11.1**

class:  **SearchRequestBuilder.java**  Method: **invoke**

```

try {
                JsonParser parser = JsonUtils.getObjectReader().getFactory().createParser(inputStream);

                try {
                    parser.nextToken();
                    boolean stop = false;

                    while(!stop && parser.nextToken() != JsonToken.END_OBJECT) {
                        String field = parser.getCurrentName();
                        parser.nextToken();
                        if (field.equals("schemas")) {
                            parser.skipChildren();

```

as **String field = parser.getCurrentName();**  returns  NULL, so **field** NULL.

field.equals()  throws error ...

I am checking this with Valid SCIM2 schema , JSON is perfectly valid.

Scim JSON:

```

[
    {
        "schemas": [
            "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
        ],
        "id": "ResourceType",
        "meta": {
            "resourceType": "ResourceType",

.....rest of json here ...

```

code throws Error  on first **{**  after **[**

```

nextToken: START_ARRAY, id: 3, value: null, location: [Source: (org.glassfish.jersey.message.internal.EntityInputStream); line: 1, column: 2], text: null
nextToken: START_OBJECT, id: 1, value: null, location: [Source: (org.glassfish.jersey.message.internal.EntityInputStream); line: 2, column: 6], text: null


Exception in thread "main" java.lang.NullPointerException
	at com.unboundid.scim2.client.requests.SearchRequestBuilder.invoke(SearchRequestBuilder.java:280)
	at com.unboundid.scim2.client.requests.SearchRequestBuilder.invoke(SearchRequestBuilder.java:155)
	at com.unboundid.scim2.client.ScimService.getResourceTypes(ScimService.java:113)


```

**Comment by papegaaij** [comment]
The problem seems to be that the `ResourceTypes` resource returns a JSON array as top level element and not an object with a `Resources` property containing the actual resources. This breaks the `getResourceTypes` method.

**Comment by kqarryzada** [comment]
This will be resolved in the upcoming 4.0.0 release of the UnboundID SCIM 2 SDK. If there are still any problems, please open a new issue.

**Comment by kqarryzada** [comment]
This fix has now been released in 4.0.0.
