### ISSUE TITLE
Handle Timestamps

### ISSUE THREAD

**Issue by numeralnathan** [pingidentity/scim2#172]
**Describe the bug**

Timestamps are not supported.

```
...
Caused by: com.unboundid.scim2.common.exceptions.BadRequestException: Unexpected character '-09-01T00:00:00Z' at position 36
at com.unboundid.scim2.common.exceptions.BadRequestException.invalidFilter(BadRequestException.java:137)
at com.unboundid.scim2.common.utils.Parser.readFilter(Parser.java:760)
at com.unboundid.scim2.common.utils.Parser.parseFilter(Parser.java:167) 
...
```
**To Reproduce**

Pass `user co ".com" AND createdAt lt 2022-09-01T00:00:00Z` to `Parser.parseFilter()`.

**Expected behavior**

I expect the code to properly handle the timestamp.

**Additional context**
 - Java version: 11
 - SCIM 2 SDK version: 2.3.7 master

**Comment by numeralnathan** [comment]
The SCIM specification says that timestamps must be enclosed with ".
